// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsFJ7Pmpf43QudMTYBWgEu3vEpg-3FlSE',
    appId: '1:477665231811:web:06d88aa024b7fb90f6f376',
    messagingSenderId: '477665231811',
    projectId: 'pharmacy-inventorymanagementdb',
    authDomain: 'pharmacy-inventorymanagementdb.firebaseapp.com',
    storageBucket: 'pharmacy-inventorymanagementdb.firebasestorage.app',
    measurementId: 'G-XGBBMHFS4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1dtQj-mViRYxIZx-0qHLFP9YvuUYf74',
    appId: '1:477665231811:android:8111bfb3709e2e1af6f376',
    messagingSenderId: '477665231811',
    projectId: 'pharmacy-inventorymanagementdb',
    storageBucket: 'pharmacy-inventorymanagementdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbPo8Bq8rxw_e-3hQwcj9r8Lx-HZOtsk',
    appId: '1:477665231811:ios:cbe5bb969702c769f6f376',
    messagingSenderId: '477665231811',
    projectId: 'pharmacy-inventorymanagementdb',
    storageBucket: 'pharmacy-inventorymanagementdb.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyInventorymanagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgbPo8Bq8rxw_e-3hQwcj9r8Lx-HZOtsk',
    appId: '1:477665231811:ios:cbe5bb969702c769f6f376',
    messagingSenderId: '477665231811',
    projectId: 'pharmacy-inventorymanagementdb',
    storageBucket: 'pharmacy-inventorymanagementdb.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyInventorymanagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsFJ7Pmpf43QudMTYBWgEu3vEpg-3FlSE',
    appId: '1:477665231811:web:a564914e24805130f6f376',
    messagingSenderId: '477665231811',
    projectId: 'pharmacy-inventorymanagementdb',
    authDomain: 'pharmacy-inventorymanagementdb.firebaseapp.com',
    storageBucket: 'pharmacy-inventorymanagementdb.firebasestorage.app',
    measurementId: 'G-S5L9FR2Z3H',
  );
}
